### ISSUE TITLE
Udarbejdelse af Scrum-præsentation

### ISSUE THREAD

**Issue by AliHMohammad** [AeselCSS/cyba-1st-semester-project-kea#58]

**Comment by YawHB** [comment]
Alle skal være klar til torsdag kl 09:00

**Comment by AeselCSS** [comment]
- [ ] Introduktion af gruppe og projekt (slide 2 + 3) Ali
- [ ] Scrum & XP metoder ( slide 4 + 5)  Chris
- [ ] Definition of done / Sprint-længde & Produkt backlog (6+7+8+9) Brian & Ali
- [x] Sprints - planning, reviews, retrospektive (10+11+12) Yaw
